bite_my_ass = 'https://raw.githack.com/Bismarck-GM/microverse-ruby-bot/base-bot-template/responses_links/bitemyass.html'
go_to_heaven = 'https://raw.githack.com/Bismarck-GM/microverse-ruby-bot/base-bot-template/responses_links/gotoheaven.html'
go_to_hell = ''
hypnotoad = 'https://raw.githack.com/Bismarck-GM/microverse-ruby-bot/base-bot-template/responses_links/hypnotoad.html'
help = ''
question = ''
no_match = ''
trivia_link = ''