@trivia_hash = { '#1' => 'It is owned by The Curiosity Company and Twentieth Century Fox.',
                 '#2' => 'The show began in 1999. During the course of the series',
                 '#3' => 'It is classed as an animated science-fiction comedy.',
                 '#4' => 'The show aired reruns on Cartoon Network’s Adult Swim channel.',
                 '#5' => 'There has been a colossal amount of merchandising for the show.',
                 '#6' =>
                 'Futurama entered the Guinness World Records with “Current Most Critically Acclaimed Animated Series”',
                 '#7' =>
                 'The show is centerd around a cryogenically frozen pizza delivery boy and his gang of motley friends.',
                 '#8' => 'Futurama is set in New York City in the 31st Century.',
                 '#9' => 'Phillip J. Fry (also known as Fry) was frozen when he delivered pizza for Panucci’s Pizza.',
                 '#10' => 'Fry possess no Delta Brain Waves',
                 '#11' => 'Turanga Leela (also known as Leela) is a cycloptic mutant.',
                 '#12' => 'Turanga Leela name is derived from the fourth Doctor’s companion',
                 '#13' => 'Bender Bending RodrÃ­guez was a failed Bending Unit 22',
                 '#14' => 'Bender suffers from kleptomania.',
                 '#15' => 'John A. Zoidberg is a Decapodian alien who practises medicine.',
                 '#16' => 'Zoidberg has a doctorate in art history.',
                 '#17' => 'Professor Hubert J. Farnsworth was deeply in love with evil genius Mom.',
                 '#18' => 'Professor Farnsworth is an honorary member of the Harlem Globetrotters.',
                 '#19' => 'Amy Wong is part of a family who owns the Western hemisphere and raise buggalos.',
                 '#20' => 'Amy is married to Kif',
                 '#21' => 'Hermes Conrad is a Jamaican bureaucrat at grade 34',
                 '#22' => 'Hermes Conrad has a young son',
                 '#23' => 'Zapp Brannigan is the captain of the Earth Ship Nimbus.',
                 '#24' => 'Brannigan has a deep infatuation with Leela.',
                 '#25' => 'Mom masquerades as the nicest mother of all robots',
                 '#26' => 'Mom masquerades has dated frenemies',
                 '#27' => 'Lord Nibbler the Nibblonian is responsible for freezing Fry.',
                 '#28' => 'Nibbler’s poop is actually dark matter',
                 '#29' => 'Futurama was created by Matt Groening (the man behind The Simpsons).' }

@quote_history = {}
